---
- name: Ensure that container home directory exists.
  ansible.builtin.file:
    path: "{{ box.home }}"
    state: directory
    mode: "0755"

- name: Create the container.
  ansible.builtin.command:
    cmd: >
      distrobox create -i {{ box.image }}
      -n {{ box.name }}
      -H {{ box.home }}
      --init-hooks "sudo pacman -Syu --noconfirm python"
  register: dc
  changed_when: "'already exists' not in dc.stdout"

- name: Run the container
  ansible.builtin.command:
    cmd: distrobox enter {{ box.name }}
  changed_when: false
