---
- name: Ensure locale is correct.
  become: true
  community.general.locale_gen:
    name: en_US.UTF-8
    state: present

- name: Ensure essential packages are installed
  become: true
  community.general.pacman:
    name:
      - zsh
      - git
      - curl
      - wget
      - openssh
      - neofetch
      - neovim
      - gitui
    state: present
