---
- name: Clone ohmyzsh repository
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    depth: 1
    version: master
    dest: ~/.oh-my-zsh

- name: Clone syntax highlighting repository
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    depth: 1
    version: master
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

- name: Clone autosuggestions repository
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    depth: 1
    version: master
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

- name: Ensure user shell is set to zsh
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    shell: /usr/bin/zsh

- name: Copy zsh confuguration
  ansible.builtin.copy:
    src: files/zshrc
    dest: ~/.zshrc
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
