---
- name: Create softlinks from host to $HOME
  ansible.builtin.file:
    src: "/home/{{ ansible_user }}/{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: link
  loop:
    - src: ".ssh"
      dest: "~/.ssh"
