---
- name: Create softlinks from host to $HOME
  ansible.builtin.file:
    src: "/home/{{ ansible_user }}/{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: link
  loop:
    - src: ".ssh"
      dest: "~/.ssh"

- name: Create softlinks for distrobox-host-exec
  become: true
  ansible.builtin.file:
    src: "/usr/bin/distrobox-host-exec"
    dest: "/usr/local/bin/{{ item }}"
    state: link
  loop:
    - podman
    - vagrant
    - virsh
    - distrobox
