---
- name: Ensure rofi config directory exists.
  ansible.builtin.file:
    path: "~/.config/rofi"
    state: directory
    mode: "0755"

- name: Set rofi theme.
  ansible.builtin.lineinfile:
    path: "~/.config/rofi/config.rasi"
    regexp: "^@theme"
    line: '@theme "~/dotfiles/config/rofi/themes/dark.rasi"'
