---
- name: Ensure base-devel is installed.
  become: true
  community.general.pacman:
    name:
      - base-devel
    state: present
    extra_args: --needed

- name: Ensure fakeroot is installed.
  become: true
  community.general.pacman:
    name: fakeroot
    state: present

- name: Clone repository.
  ansible.builtin.git:
    repo: https://aur.archlinux.org/paru.git
    dest: /tmp/paru
    version: master
    depth: 1

- name: Build paru.
  ansible.builtin.command:
    chdir: /tmp/paru
    cmd: "makepkg -si --noconfirm"
    creates: "/usr/sbin/paru"
