---
- name: Ensure that container home directory exists.
  ansible.builtin.file:
    path: "{{ box_home }}"
    state: directory
    mode: "0755"

- name: Create the container.
  ansible.builtin.command:
    cmd: >
      distrobox create -i {{ box_image }}
      -n {{ box_name }}
      -H {{ box_home }}
  register: dc
  changed_when: "'already exists' not in dc.stdout"

- name: Run the container
  ansible.builtin.command:
    cmd: distrobox enter {{ box_name }}
  changed_when: false
