---
- name: Ensure build directory exists.
  ansible.builtin.file:
    path: "{{ build_dir }}"
    state: directory
    mode: "0755"

- name: Prepare containerfile.
  ansible.builtin.template:
    src: templates/{{ box_os_family }}.Containerfile.j2
    dest: "{{ build_dir }}/Containerfile"
    mode: "0644"

- name: Build image.
  containers.podman.podman_image:
    name: "{{ custom_image_name }}"
    state: build
    path: "{{ build_dir }}"
