---
- name: Pull a base container image
  containers.podman.podman_image:
    name: "{{ base_image_name }}"
    state: present
  notify: Build custom image.

- name: Check if the box image already exists
  containers.podman.podman_image_info:
    name: "{{ custom_image_name }}"
  register: current
  changed_when: "current.images | length == 0"
  notify: Build custom image.

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
