---
- name: Create a container with distrobox
  hosts: localhost
  connection: local
  vars:
    box_name: arch
    box_os_family: "archlinux"
    base_image_name: "docker.io/library/archlinux:latest"

  roles:
    - image
    - box

- name: Provision the box
  hosts: arch
  connection: podman
  remote_user: pl

  roles:
    - essentials
    - ohmyzsh
    - dotfiles
    - neovim
    - rofi
    - paru
    - aur
