---
- name: Create a container with distrobox
  hosts: localhost
  connection: local
  vars:
    box:
      name: arch
      image: library/archlinux:latest
      home: ~/box/arch

  tasks:
    - name: Create the container.
      ansible.builtin.import_tasks: tasks/create_container.yml

- name: Provision the container
  hosts: arch
  remote_user: pl

  tasks:
    - name: Import essentials
      ansible.builtin.import_tasks:
        file: tasks/essentials.yml

    - name: Import ohmyzsh tasks
      ansible.builtin.import_tasks:
        file: tasks/ohmyzsh.yml

    - name: Import dotfiles tasks
      ansible.builtin.import_tasks:
        file: tasks/dotfiles.yml
