---
- name: Ensure locale is correct.
  block:
    - name: Install locales.
      become: true
      community.general.locale_gen:
        name: "{{ item }}"
        state: present
      loop:
        - en_US.UTF-8
        - zh_TW.UTF-8
  rescue:
    - name: Force reinstallation of glibc to generate missing locale.
      become: true
      ansible.builtin.command:
        cmd: "pacman -Sy --noconfirm glibc"
      changed_when: false

- name: Ensure essential packages are installed
  become: true
  community.general.pacman:
    name: "{{ essential_packages }}"
    state: present

- name: Import softlinks
  ansible.builtin.import_tasks: softlinks.yml
